/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.battleshippresentacion.vista;

import com.mycompany.battleshippresentacion.ivista.IVistaDatosJugador;
import com.mycompany.battleshippresentacion.modelo.ModeloPartida;
import com.mycompany.battleshippresentacion.presentador.PresentadorPrincipal;
import com.mycompany.battleshippresentacion.presentador.PresentadorUnirsePartida;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;

/**
 *
 * @author JoseH
 */
public class PantallaIngresarCodigo extends javax.swing.JPanel implements IVistaDatosJugador {

    private PresentadorPrincipal navegacion;
    private PresentadorUnirsePartida unirsePartida;
    private JFrame framePrincipal;

    /**
     * Creates new form PantallaMostrarCodigo
     */
    public PantallaIngresarCodigo(JFrame framePrincipal) {
        this.framePrincipal = framePrincipal;
        this.navegacion = new PresentadorPrincipal(framePrincipal);
        this.unirsePartida = new PresentadorUnirsePartida(this);
        initComponents();
        cargarFuentes();
    }

    private void cargarFuentes() {
        try {
            Font fuentePersonalizada = Font.createFont(Font.TRUETYPE_FONT, new File("src/main/resources/fonts/Micro5-Regular.ttf"));
            fuentePersonalizada = fuentePersonalizada.deriveFont(45f);
            lblIndicacion.setFont(fuentePersonalizada);
            btnIngresar.setFont(fuentePersonalizada);

        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIndicacion = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtCodigoSala = new javax.swing.JTextField();
        lblPergamino = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1440, 800));
        setMinimumSize(new java.awt.Dimension(1440, 800));
        setPreferredSize(new java.awt.Dimension(1440, 800));
        setLayout(null);

        lblIndicacion.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblIndicacion.setText("Ingrese el código de la sala:");
        add(lblIndicacion);
        lblIndicacion.setBounds(520, 360, 450, 40);

        btnIngresar.setBackground(new java.awt.Color(255, 137, 29));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 113, 29), 7, true));
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setMaximumSize(new java.awt.Dimension(270, 70));
        btnIngresar.setMinimumSize(new java.awt.Dimension(270, 70));
        btnIngresar.setPreferredSize(new java.awt.Dimension(270, 70));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        add(btnIngresar);
        btnIngresar.setBounds(630, 510, 170, 50);

        txtCodigoSala.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtCodigoSala.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        add(txtCodigoSala);
        txtCodigoSala.setBounds(550, 420, 320, 60);

        lblPergamino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pergamino.png"))); // NOI18N
        add(lblPergamino);
        lblPergamino.setBounds(370, 10, 668, 780);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoInicio.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 1030);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        ModeloPartida modelo = unirsePartida.unirsePartida(txtCodigoSala.getText());
        if (modelo.getCantidadJugadores() == 2) {
            navegacion.mostrarPantallaDatosJugador();
        }
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIndicacion;
    private javax.swing.JLabel lblPergamino;
    private javax.swing.JTextField txtCodigoSala;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizarVista(ModeloPartida modelo) {
        System.out.println("Si me actualice");
    }

    @Override
    public void mostrarError(String mensaje) {
        System.out.println("Error");
    }

    @Override
    public void mostrarConfiguracionJugador(ModeloPartida partida) {
        System.out.println("Si se muestra");
    }
}
