/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.battleshippresentacion.pantallas;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author JoseH
 */
public class PantallaDatosJugador extends javax.swing.JPanel {
    PantallaInicio pantallaInicio;
    
    /**
     * Creates new form PantallaDatosJugador
     */
    public PantallaDatosJugador(PantallaInicio pantallaInicio) {
        this.pantallaInicio = pantallaInicio;
        initComponents();
        cargarFuentes();
    }
    
    private void cargarFuentes(){
        try {
            Font fuentePersonalizada = Font.createFont(Font.TRUETYPE_FONT, new File("src/main/resources/fonts/Micro5-Regular.ttf"));
            fuentePersonalizada = fuentePersonalizada.deriveFont(45f);
            lblNombre.setFont(fuentePersonalizada);
            lblColor.setFont(fuentePersonalizada);
        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblColor = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JLabel();
        radioRojo = new javax.swing.JRadioButton();
        radioAzul = new javax.swing.JRadioButton();
        lblRojo = new javax.swing.JLabel();
        lblAzul = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtCodigoSala = new javax.swing.JTextField();
        lblPergamino = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1440, 800));
        setMinimumSize(new java.awt.Dimension(1440, 800));
        setPreferredSize(new java.awt.Dimension(1440, 800));
        setLayout(null);

        lblColor.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        lblColor.setText("Elegir color:");
        add(lblColor);
        lblColor.setBounds(490, 320, 200, 40);

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnContinuar.png"))); // NOI18N
        btnContinuar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnContinuarAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        add(btnContinuar);
        btnContinuar.setBounds(570, 580, 252, 80);

        buttonGroup1.add(radioRojo);
        radioRojo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        add(radioRojo);
        radioRojo.setBounds(790, 530, 20, 20);

        buttonGroup1.add(radioAzul);
        radioAzul.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        add(radioAzul);
        radioAzul.setBounds(620, 530, 20, 20);

        lblRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoRojo.png"))); // NOI18N
        add(lblRojo);
        lblRojo.setBounds(720, 390, 140, 120);

        lblAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoAzul.png"))); // NOI18N
        add(lblAzul);
        lblAzul.setBounds(550, 380, 150, 130);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        lblNombre.setText("Nombre:");
        add(lblNombre);
        lblNombre.setBounds(490, 180, 120, 40);

        txtCodigoSala.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        txtCodigoSala.setEnabled(false);
        add(txtCodigoSala);
        txtCodigoSala.setBounds(490, 230, 400, 60);

        lblPergamino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pergamino.png"))); // NOI18N
        add(lblPergamino);
        lblPergamino.setBounds(370, 10, 668, 780);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoInicio.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 1030);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnContinuarAncestorAdded
        PantallaColocarBarcos pantallaSiguiente = new PantallaColocarBarcos(pantallaInicio);
        pantallaInicio.getContentPane().removeAll();
        pantallaInicio.setLayout(new BorderLayout());

        // Agregar el nuevo JPanel al JFrame
        pantallaInicio.add(pantallaSiguiente, BorderLayout.CENTER);
        pantallaInicio.revalidate();                   
        pantallaInicio.repaint();
        pantallaSiguiente.setVisible(true);
    }//GEN-LAST:event_btnContinuarAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnContinuar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAzul;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPergamino;
    private javax.swing.JLabel lblRojo;
    private javax.swing.JRadioButton radioAzul;
    private javax.swing.JRadioButton radioRojo;
    private javax.swing.JTextField txtCodigoSala;
    // End of variables declaration//GEN-END:variables
}
